version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/elasticsearch/data:/run/elasticsearch-2.3.3/data

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
