version: '2'

services:
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - /opt/esdata:/run/elasticsearch-2.3/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
